<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-set-password_</name>
   <tag></tag>
   <elementGuidId>309e7ae7-5165-4a2d-8fcf-5639c1ea936b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-set-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_login']/div/div/div/app-set-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-set-password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> กำหนดรหัสผ่าน รหัสผ่านยืนยัน รหัสผ่าน ตกลง  ยกเลิก </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_login&quot;)/div[@class=&quot;login-aside d-flex flex-column flex-row-auto&quot;]/div[@class=&quot;flex-row-fluid d-flex flex-column justify-content-center position-relative overflow-hidden p-7 mx-auto&quot;]/div[@class=&quot;d-flex flex-column-fluid flex-center ustify-content-center&quot;]/app-set-password[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_login']/div/div/div/app-set-password</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-set-password</value>
   </webElementXpaths>
</WebElementEntity>
