<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1   2</name>
   <tag></tag>
   <elementGuidId>44fa42f3-c97a-4ca8-a6cf-1ded26ddc803</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='kt_form']/div[2]/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-xl-12 > div.form-group</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-group</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>สํานักงานเขตพื้นที่การศึกษา หรือสํานักงาน กศน.จังหวัด/กรุงเทพมหานคร สำนักงานเขตพื้นที่การศึกษามัธยมศึกษากรุงเทพมหานคร เขต 1 สำนักงานเขตพื้นที่การศึกษามัธยมศึกษากรุงเทพมหานคร เขต 2 สำนักงานเขตพื้นที่การศึกษามัธยมศึกษากาญจนบุรี สำนักงานเขตพื้นที่การศึกษามัธยมศึกษากาฬสินธุ์ สำนักงานเขตพื้นที่การศึกษามัธยมศึกษากำแพงเพชร สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาขอนแก่น สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาจันทบุรี ตราด สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาฉะเชิงเทรา สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาชลบุรี ระยอง สำนักงานเขตพื้นที่การศึกษามัธยมศึกษาชัยภูมิ </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_form&quot;)/div[@class=&quot;pb-5&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-12&quot;]/div[@class=&quot;form-group&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='kt_form']/div[2]/div[4]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ข้อมูลหน่วยงาน'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
