<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1.  2. 3</name>
   <tag></tag>
   <elementGuidId>be159cde-5222-41ba-95a9-a0e090e23a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_content']/div/div/app-register/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1. ตรวจสอบ อีเมล2. ข้อมูลลงทะเบียน3. ผลการลงทะเบียน  อีเมลสำหรับเข้าใช้ระบบ * ข้อมูลผู้ลงทะเบียน เลขบัตรประชาชน *คำนำหน้า *ชื่อ *นามสกุล *วันเกิด ตำแหน่ง *หมายเลขโทรศัพท์ * ข้อมูลหน่วยงาน สํานักงานเขตพื้นที่การศึกษา หรือสํานักงาน กศน.จังหวัด/กรุงเทพมหานคร  ย้อนกลับ  ปิด  ดำเนินการต่อ </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_content&quot;)/div[@class=&quot;d-flex flex-column-fluid&quot;]/div[@class=&quot;container&quot;]/app-register[1]/div[@class=&quot;py-15 mt-15&quot;]/div[@class=&quot;card card-custom gutter-b&quot;]/div[@class=&quot;card-body&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_content']/div/div/app-register/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ลงทะเบียนผู้ดูแลระบบสํานักงานเขตพื้นที่การศึกษา หรือสํานักงาน กศน.จังหวัด/กรุงเทพมหานคร'])[1]/following::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ระบบการประเมินวิทยฐานะสำหรับข้าราชการครูและบุคลากรทางการศึกษา'])[1]/following::div[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
   </webElementXpaths>
</WebElementEntity>
